### ISSUE TITLE
is this lib suport IE 7 and 8 ?

### ISSUE THREAD

**Issue by hongyin163** [treycordova/nativejsx#12]

**Comment by treycordova** [comment]
The transpiled code will run without a problem in IE7 and 8.

**Comment by hongyin163** [comment]
when i use "Webpack: nativejsx-loader" in my project
the file "https://github.com/treycordova/nativejsx/blob/master/dist/nativejsx-prototypes.js" will have problem, because there is't htmlelement type in ie7
so is there some method to expend dom to surport appendChildren in ie7 ？

**Comment by treycordova** [comment]
Alright, IE7 and 8 do have lacking support for `HTMLElement`. I apologize for being quick to dismiss the issue. Considering that both browsers are no longer supported by Microsoft, I'm going to keep this issue closed. If you feel that this library should support them, then submit a pull request at your leisure.
