### ISSUE TITLE
All null literals in all ternary operators get replaced with noscript elements

### ISSUE THREAD

**Issue by odzb** [treycordova/nativejsx#15]
We are using `nativejsx` in a large legacy code base which gets sparsely interspersed with small pieces of JSX. It appears that whenever there is a ternary operator, all `null` literals get replaced with `noscript` element creation code. This happens even in code with no JSX nearby. It's a major issue for us because DOM elements are truthy values, while nulls are falsy, and stuff starts breaking in obscure ways.

We could isolate our JSX in files with another file extension, but it would be inferior to the way you normally use JSX in case of React+Babel. We don't need the `noscript`s at all, so it would be nice to at least be able to configure `nativejsx` not to do that replacement.

**Comment by treycordova** [comment]
Alright, I'm thinking about completely removing `<noscript>` logic. Here's [the commit](https://github.com/treycordova/nativejsx/commit/e847395a8f18545a8f8552c42b6cda727bcba24c). I can't deem a good enough reason to keep it around with `appendChildren`.

**Comment by treycordova** [comment]
`<noscript>` is dead with [4.0.0](https://github.com/treycordova/nativejsx/tree/4.0.0).
