### ISSUE TITLE
Can't use `this` in JSX

### ISSUE THREAD

**Issue by odzb** [treycordova/nativejsx#17]
If I want to use `this` in my JSX like this:
```
<div onMouseDown={this.handleMouseDown.bind(this)}>
```
Then it just won't work, because generated code gets enclosed in an IIFE which is not an arrow function.

**Comment by treycordova** [comment]
Alright, my solution to this problem is the following:
```jsx
const element = <div onClick={this.onClick.bind(this)} />
```
Transpiles to
```js
const element = function() {
  var $$a = document.createElement('div');
  $$a.addEventListener(this.onClick.bind(this));
  return $$a;
}.call(this);
```
I'd like to point out `.call(this)`. That'll pipe through `this` anywhere JSX is used. It'll be up to the user to pipe it through larger expressions. That can be accomplished using arrow functions.
```js
const element = (
  <ul>
    {[1, 2, 3].map(() => {
      return <li onClick={this.onClick.bind(this)} />
    }}
  </ul>
)
```

**Comment by odzb** [comment]
Looks good to me, thank you!

**Comment by treycordova** [comment]
Closing this up with the release of [4.0.0](https://github.com/treycordova/nativejsx/tree/4.0.0). Thanks again!
