### ISSUE TITLE
How can I save the dom reference?

### ISSUE THREAD

**Issue by j3l11234** [treycordova/nativejsx#20]
As the title
I want to save the reference of some dom.
maybe we can set a callback on the  'ref' prop ? just like react 
: )

**Comment by treycordova** [comment]
Referencing a node can be accomplished through `querySelector`:
```js
const element = (
  <div className="root-node">
    <div className="child"/>
  </div>
);

const child = element.querySelector('.child');
// Or
this.child = element.querySelector('.child');
```
Will this work for you?

**Comment by treycordova** [comment]
Thanks for adding `ref`! 🙂
