### ISSUE TITLE
Can't put JSX in object props

### ISSUE THREAD

**Issue by odzb** [treycordova/nativejsx#22]
Of these props, only `four` will compile successfully:
```
const test = {
    one: <div className="test1"></div>,
    two: (<div className="test2"></div>),
    three: (() => <div className="test3"></div>)(),
    four: (() => {return <div className="test4"></div>})()
};
```

**Comment by treycordova** [comment]
Here's the fix: https://github.com/treycordova/nativejsx/commit/52770907fb942fdfa94887283e3d6a7b0066f8e1! Thanks for reporting the issue.

**Comment by odzb** [comment]
Awesome! Could you please push version 4.2.0 to NPM? It currently only shows 4.1.0 at https://www.npmjs.com/package/nativejsx
