### ISSUE TITLE
Missing nativejsx-prototype.js 

### ISSUE THREAD

**Issue by asunar** [treycordova/nativejsx#5]
> Use a very tiny JavaScript file located in dist, nativejsx-prototype.js. Feel free to include it in your build steps (before any nativejsx-transpiled code runs, of course).

Cannot see nativejsx-prototype.js in dist folder.

**Comment by treycordova** [comment]
Ah! That slipped by during the rebranding. Just use the jsxdom equivalent for now. I'll get the nativejsx versions up and released by the end of the day.

Thanks for catching that @asunar!

**Comment by treycordova** [comment]
Fixed. Thanks again!
