### ISSUE TITLE
Running nativejsx from npm scripts

### ISSUE THREAD

**Issue by asunar** [treycordova/nativejsx#7]
Is it possible to run nativejsx transpilation by providing source/dest folders i.e. do exactly what gulp-nativejsx is doing without the gulp dependency?

I imagine something like this in package.json

```
   "scripts": {
    "build": "nativejsx www\\src --out www\\dist\"
   }

```
Transpile the file under src folder and save the output in dist folder

Thanks.

**Comment by treycordova** [comment]
Hmm, I haven't considered it, but I could see how that would be nice to have. I'll see if I can get something working over the weekend.

**Comment by asunar** [comment]
Thanks.

**Comment by treycordova** [comment]
Alright, there's a basic implementation sitting in master under `bin/`.

Here's an example to get you started:
```
$ bin/nativejsx test/**/*.jsx --output compiled/
```

Let me know if this works for your purposes. If so, either you or I can close out this issue.

Thanks.

**Comment by asunar** [comment]
Hi @treycordova, 
Thanks for the quick response.

I tested the implementation here are my comments:

1) bin folder does not seem to be part of the npm package. Ran npm install nativejsx in a new folder, did not get the bin folder. Can you add it to the package so that npm install will create the bin folder?

2) After manually downloading the bin folder. I tried to run nativejsx from npm scripts section. It only worked successfully when I ran it from the command line like this:

`node node_modules\nativejsx\bin\nativejsx ./test/repro.js --output compiled/`

I was hoping to run nativejsx with npm run.
In package.json, if there is a build command in scripts section like this:
```
   "scripts": {
    "build": "nativejsx test/**/*.jsx --output compiled/"
   }
```
I would like to run nativejsx like this:
`npm run build`

Here is a typical implementation. After installing uglifyjs with npm install and adding the following line to package.json
```
   "scripts": {
    "build": "uglifyjs www\\script-compiled.js -o www\\script-compiled.min.js"
   }
```
I can run it successfully like this:
`npm run build`

A better user experience in my opinion because

1. npm install downloads everything that is needed
2. User can run the package with npm run xxxxx
3. User does not have to worry about figuring the full path

Would it be possible to address these issues? I'll see if I can create a pull request to address them.

Thanks.

**Comment by asunar** [comment]
Looks like adding a bin section to your package.json is a good place to start.
[npm and executables](http://markmarkoh.com/nodejs-npm-and-executables/)

**Comment by treycordova** [comment]
I apologize for not being clearer (also I was in Europe, so I kind of disappeared on you).

I was wondering if the binary worked as you expected _without_ a release of `nativejsx`. I'm going to go with my confirmation and say it works, and I've added it to `bin` and cut a release. It's available in [3.1.0](https://github.com/treycordova/nativejsx/releases/tag/3.1.0) (and installable through npm) and should have the user experience that you desired.

Thanks for all of the suggestions and thanks for helping out, @asunar.

**Comment by asunar** [comment]
HI @treycordova,
Sorry for pointing out the obvious. I did not realize that you wanted to verify the binary before updating the package.

Thanks for updating the package. It seems to be working with a single file but not with wildcards.
i.e. This works
`nativejsx components/repro.js --output dist/`

but this does not work
`nativejsx components/*.js --output dist/`
`> Error: ENOENT: no such file or directory, open 'c:\code\mynativejsx\components\*.js'`

neither does this
`nativejsx components/**/*.js --output dist/`
`>Error: ENOENT: no such file or directory, open 'c:\code\mynativejsx\components\**\*.js'`

When you have some time can you add wildcard support?

Thanks for all the effort.

**Comment by treycordova** [comment]
Mind trying out 2769cbce921076bebb4906f66de7b9ca01ac4c4a?

**Comment by asunar** [comment]
typeof files is object so it does not glob it.

![glob](https://cloud.githubusercontent.com/assets/204049/14585367/4668c806-0437-11e6-8f3f-827a0173fc2c.png)

**Comment by treycordova** [comment]
Can I get an output of `files` to see what we're dealing with.

**Comment by asunar** [comment]
Looks like It is an array.
![glob](https://cloud.githubusercontent.com/assets/204049/14585383/5920da8c-0438-11e6-9601-bad4d310cbd1.png)

**Comment by treycordova** [comment]
Alright, this one (https://github.com/treycordova/nativejsx/commit/0995154b1bef6e0907da55cef1209aaf9cde8865) is going to work (crosses fingers).

**Comment by asunar** [comment]
It worked.. 
:tada: 

Thanks again, much appreciated.

**Comment by treycordova** [comment]
Tagged and published. You can `npm update nativejsx`. It's now at [3.1.1](https://github.com/treycordova/nativejsx/releases/tag/3.1.1). I'm going to close this one out.

**Comment by asunar** [comment]
:+1:
